# Generated by Django 5.2.1 on 2025-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weekly_cashback",
            field=models.FloatField(default=0.0),
        ),
    ]
