# Generated by Django 5.2.1 on 2025-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_withdrawrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="lay",
            name="file",
            field=models.ImageField(default="", upload_to="lays/"),
            preserve_default=False,
        ),
    ]
