# Generated by Django 5.2.1 on 2025-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_lay_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="lay",
            name="match",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lay",
            name="tip",
            field=models.CharField(default="", max_length=255),
        ),
    ]
