# Generated by Django 5.2.1 on 2025-09-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_lay_match_lay_tip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lay",
            name="loss_payout",
            field=models.CharField(default="", max_length=255),
        ),
    ]
