# Generated by Django 5.2.1 on 2025-09-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_lay_loss_payout"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lay",
            name="approval_status",
            field=models.CharField(
                choices=[("active", "Active"), ("history", "History")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
