# Generated by Django 5.2.1 on 2025-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_adminoptions_lay_approval_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminOptions",
        ),
        migrations.RemoveField(
            model_name="lay",
            name="approval_status",
        ),
        migrations.AlterField(
            model_name="lay",
            name="status",
            field=models.CharField(
                choices=[
                    ("declined", "Declined"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
